### ISSUE TITLE
Force combat mode for radius

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARC_Ares#2]
Units garrisoned with Ares don't react to combat. Maybe a module to enforce it when in combat would work.

**Comment by sorenjohanson** [comment]
This may be a bit tricky as the building occupation script is third party, but nothing in it (besides a doWatch command) should force the AI's hand when it comes to combat. I'll test this out throughout the day.

**Comment by sorenjohanson** [comment]
See https://github.com/ARCOMM/ARC_Ares/commit/76c12539fbac05bc09012e5757c3a377cd03909d
