### ISSUE TITLE
Headless client support

### ISSUE THREAD

**Issue by jameslkingsley** [ARCOMM/ARC_Ares#5]
A few modules such as the MTAW ones and the Hunt Nearest Player are broken now that headless client is fixed. The code is executed before HC takes ownership which means that code disappears and the unit(s) stops. We need to implement a way to `waitUntil` they're on the headless client as units are not instantly transferred (minimum of 15 seconds between transfers).

**Comment by sorenjohanson** [comment]
~~Are there commands to reliably check if a unit is under HC ownership?~~

[groupOwner](https://community.bistudio.com/wiki/groupOwner) and [owner](https://community.bistudio.com/wiki/owner) for future reference. I'll work on it tomorrow.

**Comment by sorenjohanson** [comment]
Just to double check, only both MTAW functions plus hunt nearest player are affected by this, right?

**Comment by jameslkingsley** [comment]
As far as I'm aware, yes.

**Comment by sorenjohanson** [comment]
OK, another thing. Now that HC is fixed are we guaranteed to be playing with it 100% of the time? Implementing a non-HC solution (ie if HC is not used) alongside the HC solution will be a bit more time consuming.

**Comment by jameslkingsley** [comment]
I'm not too sure. If HC breaks again in the future then it would be nice to have a backup. Maybe something similar to the `execHC` function just in Ares where you supply the code and it checks if any of the `Virtual Headless` class name entities are not null, if so then HC is active, if they're null then no HC.

**Comment by sorenjohanson** [comment]
Ares has functions to check for HC? Currently don't have a proper check if HC is properly initialized. Also sort of stuck on properly checking owner of the unit, but that's another issue.

**Comment by jameslkingsley** [comment]
Not by default no, but it shouldn't be too hard to implement something that checks if a HC is null. https://community.bistudio.com/wiki/entities might help.

**Comment by sorenjohanson** [comment]
See https://github.com/ARCOMM/ARC_Ares/tree/dev_HC as well as https://github.com/ARCOMM/ARC_Ares/commit/f19cf838201cc56fe4081659ebe281bc215adc66 

Ownership is up next

**Comment by sorenjohanson** [comment]
> (minimum of 15 seconds between transfers).

To get back to this, is this for units that are placed in mission (ie Zeus) or pre-placed in editor and then transferred over?

**Comment by jameslkingsley** [comment]
Any units spawned in editor, Zeus or MCC. It's like if 2 groups are transferred and another group spawns, straight after, it will wait the specified time before transferring again. However this delay has changed on the server to 1 second so this may not be a problem, but I have seen some delay issues with HC in Zeus lately.
